/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>

using namespace std;

class fiboVars
{
private:
	int num1 = 1;
	int num2 = 2;
	unsigned long long sum = 0; // sum of even numbers
	const unsigned long LIMIT = 4000000;
public:
	void runNumbers();
	void showEvenSum();
};

int main()
{
	fiboVars fb;

	fb.runNumbers();
	fb.showEvenSum();

}

void fiboVars::runNumbers()
{
	unsigned int temp = 0;
	while (num2 < LIMIT)
	{

		if (num2 % 2 == 0)
			sum += num2;
		
		temp = num1;
		num1 = num2;
		num2 = (temp + num1);
	}
}

void fiboVars::showEvenSum()
{
	cout << sum;
}