/*
A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

a^2 + b^2 = c^2
For example, 32 + 42 = 9 + 16 = 25 = 52.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.
*/
#include <stdio.h>
#include <inttypes.h>
#include <math.h>

using namespace std;

int main()
{
	//this solution was found when researching patterns of triples 
	//generated by using quadratic equations
	//while the equations do not hit every triple, every triple can be scalar
	//multiplied to create the missing triples
	int x = 1, y, a = 0, b = 0, c = 0, sumLimit = 1000;

	while (c < 1000)
	{
		for (y = 1; y < x; y++)
		{
			a = (x * x) - (y * y);
			b = 2 * (x * y);
			c = (x * x) + (y * y);

			if ((pow(a, 2) + pow(b, 2) == pow(c, 2)) && (a + b + c == 1000))
			{
				printf("%d", a * b * c);
				break;
			}
		}
		x += 1;
	}
}
